services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    restart: unless-stopped
    container_name: filebrowser
    ports: 
      - ${FILEBROWSER_PORT}:80
    volumes:
      - ${FILEBROWSER_PATH}:/srv