---
services:
  wikijs:
    image: lscr.io/linuxserver/wikijs:latest
    container_name: wikijs
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${WIKIJS_CONFIG}:/config
      - ${WIKIJS_DATA}:/data
    ports:
      - ${WIKIJS_PORT}:3000
    restart: unless-stopped