networks:
  proxy:
    name: proxy
    external: true
    driver: bridge
services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ${NGINX_PROXY_DATA}:/data
      - ${NGINX_PROXY_SNIPPETS}:/snippets
      - ${NGINX_PROXY_LETSENCRYPT}:/etc/letsencrypt