services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${QBITTORRENT_PORT}
    volumes:
      - ${QBITTORRENT_CONFIG}:/config
      - ${QBITTORRENT_DOWNLOADS}:/downloads
    ports:
      - ${QBITTORRENT_PORT}:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped