---
services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=3000
    volumes:
      - ${KASM_OPT}:/opt
    ports:
      - 3000:3000
      #- 443:443
    restart: unless-stopped