networks:
  proxy:
    name: proxy
    external: true
    driver: bridge
services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - ${AUTHELIA_CONFIG}:/config
    ports:
      - '127.0.0.1:9091:9091'
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=${TZ}
    healthcheck:
      disable: false