services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - ${AUTHELIA_CONFIG}:/config
    expose:
      - 9091
    restart: unless-stopped
    networks:
      - net
    environment:
      - TZ=${TZ}
    healthcheck:
      disable: false