services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - TZ=${TZ}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_NAME=${SMTP_NAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_DOMAIN=${MAIL_DOMAIN}
    volumes:
      - ${NEXTCLOUD_CONFIG}:/config
      - ${NEXTCLOUD_DATA}:/data
    ports:
      - 443:443
      - ${NEXTCLOUD_PORT}:80
    restart: unless-stopped
    depends_on:
      - postgres

  collabora:
    image: collabora/code:latest
    container_name: collabora
    restart: unless-stopped
    environment:
      - username=${COLLABORA_USERNAME}
      - password=${COLLABORA_PASSWORD}
      - dictionaries=en_US
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
    ports:
      - ${COLLABORA_PORT}:9980
    depends_on:
      - nextcloud
